[usage]
reportName = "Extracts student score data by domain to calc-fields of a student-oriented record"
activated = true
outputFileName = "./out/null/domainresponsesscores.csv"


[[fields]]
"no-op" = "no-op"
# no fields needed for this report