[usage]
reportName = "Splitter Block (supports splitting reports by school, yr level & domain)"
activated = true
outputFileName = "./out/null/eventrecordsplitterblock.csv"


[[fields]]
"no-op" = "no-op"

