[usage]
reportName = "Splitter Block for Student Oriented reports (supports splitting reports by school & yr level)"
activated = true
outputFileName = "./out/null/blocksplitter.csv"


[[fields]]
"no-op" = "no-op"

