[usage]
reportName = "Item Response Extractor (separates item-respoonses)"
activated = true
outputFileName = "./out/null/itemextractor.csv"


[[fields]]
"no-op" = "no-op"
# no fields needed for this report