[usage]
reportName = "Home Schooled Test Participants (SA spec.)"
activated = true
outputFileName = "./out/system_reports/saHomeschooledTests.csv"

# order of fileds below is left to right order
# columns will appear in final output, can be changed as needed.
# commenting out a ke/value pair will remove that column from the
# final report
[[fields]]
"School" = "CalculatedFields.SchoolId"
[[fields]]
"YrLevel" = "CalculatedFields.YrLevel"
[[fields]]
"Domain" = "CalculatedFields.Domain"
#
# fields ablve are for report splitting 
#

[[fields]]
"PSI" = "NAPEventStudentLink.PlatformStudentIdentifier"
[[fields]]
"School Student ID" = "StudentPersonal.LocalId"
[[fields]]
"First name" = "StudentPersonal.PersonInfo.Name.GivenName"
[[fields]]
"Middle name" = "StudentPersonal.PersonInfo.Name.MiddleName"
[[fields]]
"Last name" = "StudentPersonal.PersonInfo.Name.FamilyName"
[[fields]]
"Preferred name" = "StudentPersonal.PersonInfo.Name.PreferredName"
[[fields]]
"Date of Birth"= "StudentPersonal.PersonInfo.Demographics.BirthDate"
[[fields]]
"Sex" = "StudentPersonal.PersonInfo.Demographics.Sex"
[[fields]]
"School Sector" = "SchoolInfo.SchoolSector"
[[fields]]
"School ACARA ID" = "SchoolInfo.ACARAId"
[[fields]]
"School name" = "SchoolInfo.SchoolName"
# Not available -  "School suburb" = "School.Address.0.City"
[[fields]]
"Year Level" = "StudentPersonal.MostRecent.YearLevel.Code"
[[fields]]
"Test name" = "NAPTest.TestContent.TestName"
[[fields]]
"Test Attempt Status" = "NAPEventStudentLink.ParticipationCode"
[[fields]]
"Reporting School ID" = "StudentPersonal.MostRecent.ReportingSchoolId"
[[fields]]
"Reporting School Name" = "NAPEventStudentLink.ReportingSchoolName"

