
[usage]
reportName = "(QA) Summarises test attempts, and highlights any issues between attemtpts and responses"
activated = true
outputFileName = "./out/qa/systemTestCompleteness.csv"

# Order of fields below is left to right order
# columns will appear in final output, can be changed as needed.
# Double brackets required to ensure map is created as array to preserve order
# commenting out a key/value pair will remove that column from the
# final report
#
[[fields]]
"School" = "CalculatedFields.SchoolId"
[[fields]]
"YrLevel" = "CalculatedFields.YrLevel"
[[fields]]
"Domain" = "CalculatedFields.Domain"
#
# fields above are for report splitting 
#

[[fields]]
"ACARAID" = "CalculatedFields.SystemTestCompleteness.SchoolInfo.ACARAId"
[[fields]]
"TestDomain" = "CalculatedFields.SystemTestCompleteness.NAPTest.TestContent.Domain"
[[fields]]
"TestLevel" = "CalculatedFields.SystemTestCompleteness.NAPTest.TestContent.TestLevel.Code"
[[fields]]
"P_Attempts_Count" = "CalculatedFields.SystemTestCompleteness.P_AttemptsCount"
[[fields]]
"S_Attempts_Count" = "CalculatedFields.SystemTestCompleteness.S_AttemptsCount"
[[fields]]
"R_Attempts_Count" = "CalculatedFields.SystemTestCompleteness.R_AttemptsCount"
[[fields]]
"Total Attempts" = "CalculatedFields.SystemTestCompleteness.TotalAttemptsCount"
[[fields]]
"Responses_Count" = "CalculatedFields.SystemTestCompleteness.TotalResponsesCount"
[[fields]]
"Attempts_With_No_Response" = "CalculatedFields.SystemTestCompleteness.ANRList.#.ANR"
[[fields]]
"Responses_With_No_Attempt" = "CalculatedFields.SystemTestCompleteness.RNAList.#.RNA"
