
[usage]
reportName = "(QA) Reports a row for every test administered at a different test level from the year level that the student was enrolled in"
activated = true
outputFileName = "./out/qa/systemTestYearLevelDiscrepancies.csv"

# Order of fields below is left to right order
# columns will appear in final output, can be changed as needed.
# Double brackets required to ensure map is created as array to preserve order
# commenting out a key/value pair will remove that column from the
# final report
#
[[fields]]
"School" = "CalculatedFields.SchoolId"
[[fields]]
"YrLevel" = "CalculatedFields.YrLevel"
[[fields]]
"Domain" = "CalculatedFields.Domain"
#
# fields above are for report splitting 
#

[[fields]]
"Family Name" = "StudentPersonal.PersonInfo.Name.FamilyName"
[[fields]]
"Given Name" = "StudentPersonal.PersonInfo.Name.GivenName"
[[fields]]
"Birth Date" = "StudentPersonal.PersonInfo.Demographics.BirthDate"
[[fields]]
"Test Name" = "NAPTest.TestContent.TestName"
[[fields]]
"Test Year-Level" = "NAPTest.TestContent.TestLevel.Code"
[[fields]]
"Student Year-Level" = "StudentPersonal.MostRecent.YearLevel.Code"
[[fields]]
"PSI" = "StudentPersonal.OtherIdList.OtherId.#[Type==NAPPlatformStudentId].value"
