
[usage]
reportName = "(QA) Reports errors when response items contain unexpected information based on the participation code"
activated = true
outputFileName = "./out/qa/systemParticipationCodeItemImpacts.csv"

# Order of fields below is left to right order
# columns will appear in final output, can be changed as needed.
# Double brackets required to ensure map is created as array to preserve order
# commenting out a key/value pair will remove that column from the
# final report
#
[[fields]]
"School" = "CalculatedFields.SchoolId"
[[fields]]
"YrLevel" = "CalculatedFields.YrLevel"
[[fields]]
"Domain" = "CalculatedFields.Domain"
#
# fields above are for report splitting 
#

[[fields]]
"ACARA ID" = "SchoolInfo.ACARAId"
[[fields]]
"School Name" = "SchoolInfo.SchoolName"
[[fields]]
"Test Level" = "NAPTest.TestContent.TestLevel.Code"
[[fields]]
"Test Domain" = "NAPTest.TestContent.Domain"
[[fields]]
"Participation Code" = "NAPEventStudentLink.ParticipationCode"
[[fields]]
"Family Name" = "StudentPersonal.PersonInfo.Name.FamilyName"
[[fields]]
"Given Name" = "StudentPersonal.PersonInfo.Name.GivenName"
[[fields]]
"Birth Date" = "StudentPersonal.PersonInfo.Demographics.BirthDate"
[[fields]]
"PSI" = "StudentPersonal.OtherIdList.OtherId.#[Type==NAPPlatformStudentId].value"
[[fields]]
"Test Item Local ID" = "CalculatedFields.TestItem.TestItemContent.NAPTestItemLocalId"
[[fields]]
"Test Item Name" = "CalculatedFields.TestItem.TestItemContent.ItemName"
[[fields]]
# no longer exists
# "Testlet Score" = "Response.TestletList.Testlet.0.TestletScore"
[[fields]]
"Item Score" = "CalculatedFields.ItemResponse.Score"
[[fields]]
"SubscoreList" = "CalculatedFields.ItemResponse.Subscores"
[[fields]]
"Error" = "CalculatedFields.ParticipationCodeItemImpactError"
