[usage]
reportName = "Writing Extract PSI List"
activated = true
outputFileName = "./out/writing_extract/qaPSI.csv"

# order of fileds below is left to right order
# columns will appear in final output, can be changed as needed.
# commenting out a ke/value pair will remove that column from the
# final report
[[fields]]
"PSI" = "NAPEventStudentLink.PlatformStudentIdentifier"











